---
name: Auto-bump

on:
  pull_request_review:
    types: [submitted] # Only trigger on review submissions
    branches: [main] # Your target branches

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  if: github.event.review.state == 'approved'
  auto-bump:
    name: Auto-bump and release
    runs-on: ubuntu-latest

    steps:
      - run: |
         npm install -g makecode

      - run: 'git config --global user.email "ssande@forwardedu.com"'

      - run: 'git config --global user.name "ssande-fwd"'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout and track the PR branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout -b ${{ github.event.pull_request.head.ref }} origin/${{ github.event.pull_request.head.ref }}

      - name: Count new tutorials
        id: new_tutorials
        run: >
          echo "tutorial_count="
          `
          git diff $(git describe --tags --abbrev=0):pxt.json pxt.json |
          grep -e '^[+-][^/]*.md' |
          wc -l
          `
          >> "$GITHUB_OUTPUT"

      - name: SANITY CHECK
        run: >
          echo "New tutorials: ${{ steps.new_tutorials.outputs.tutorial_count }}";
          echo "bump: "`(
          [[ ${{ steps.new_tutorials.outputs.tutorial_count }} > 0 ]] &&
          echo "minor" ) ||
          echo "patch"`;

      - run: >
          makecode bump --`(
          [[ ${{ steps.new_tutorials.outputs.tutorial_count }} > 0 ]] &&
          echo "minor" ) ||
          echo "patch"`

      - name: Merge pull request
        uses: actions/github-script@v6
        if: steps.bump_type.outputs.bump_level!= 'patch'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            return github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'merge'
            });
